name: Build and Publish Vessyl Buildenv

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vessylapp/vessyl-buildenv:${{ steps.extract_tag.outputs.tag }}
            ghcr.io/vessylapp/vessyl-buildenv:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7